USE [Tasken]
GO

CREATE TABLE [dbo].[CLIENTES](
	[Nome] [varchar](50) NULL,
	[CPF] [nchar](11) NOT NULL,
	[Idade] [int] NULL,
	CONSTRAINT PK_CPF_CLIENTES PRIMARY KEY ([CPF]) 
) 
GO


CREATE TABLE [dbo].[TELEFONES](
	[CPF_CLIENTE] [nchar](11) NOT NULL,
	[DDD] [nchar](3) NOT NULL,
	[TELEFONE] [nchar](9),
	
	CONSTRAINT FK_CPF_CLIENTE_TELEFONES_CLIENTES FOREIGN KEY ([CPF_CLIENTE])
	REFERENCES [dbo].[CLIENTES] ([CPF])
	ON DELETE CASCADE
	ON UPDATE CASCADE
)
GO

